### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#10]
- [x] #11 Systems architecture planning
- [x] #50 Set up tachyons for css styling
- [x] #12 Database setup
- [x]  Environment setup - setting up hosting and domain, server and development tools
- [x] #37 PWA - Install to home screen spike - looks possible, implementation lower priority
- [x] create developer gmail account and heroku account
- [x] #43 transfer the current heroku (spike) app to the new heroku account
- [x] #45 Add Continuous integration test and pre-commit
- [x] #53 Add [credo](https://github.com/rrrene/credo) as a linter for the application
2 days estimate

**Comment by Cleop** [comment]
Closing as a technical issue and can't be tested. All issues are now complete.
