### ISSUE TITLE
Search History

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#17]
Saving of all searches to database for future admin access
- [x] Saving search history (not on view) #35 
- [x] View of recent searches ( #34 ):
<img src="https://user-images.githubusercontent.com/16775804/28274086-cfa9e414-6b07-11e7-805c-1f80e2a17c65.png" width=250px />

- [x] History (excluding history indicating which articles/searches had notes) #71

<img src="https://user-images.githubusercontent.com/16775804/28273692-e85a5c60-6b06-11e7-82ed-bbd2366a81e0.png" width=250px />

**Comment by markwilliamfirth** [comment]
Removing this epic from the Sprint 1 milestone, as it is spread across two sprints

**Comment by markwilliamfirth** [comment]
This has now been completed and tested . - closing
