### ISSUE TITLE
Tracking Article Click-throughs using Google Analytics

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#26]
Detailed implementation of Google Analytics to track click-throughs to articles and linking of article click-throughs to the search query (the latter will require more research to understand how this can be done in Google Analytics)

- [ ] Tracking the number of times a publication is clicked on (regardless of search terms used)

- [ ] Tracking the number of times a publication is clicked on according to specific search terms

**Comment by markwilliamfirth** [comment]
Test @ajburls watching

**Comment by markwilliamfirth** [comment]
@ajburls this issue was created from the original proposal and is still in the backlog. Please could you update the priority label and add any additional information that is required?

**Comment by ajburls** [comment]
@markwilliamfirth I think the priority 3 is right. It will be important for us to be able to give to potential future funders information about how the app is being used. We are proposing to give the app to students to whom we are promoting EBP as an educational tool in September and would want to know whether they are using it.

**Comment by markwilliamfirth** [comment]
@Cleop please could you time estimate this?

**Comment by Cleop** [comment]
Currently GA gives us information on:
- number of unique and repeat users to the site (retention)
- no. of page views
- origin of users by country
- device of users e.g. mobile, tablet, desktop
- time/day of visits
- referral e.g. github
- when users click on the feedback button and which page they were on when the feedback button was clicked

**Comment by ajburls** [comment]
@Cleop these sound very useful but will we know whether they clicked through to papers and, if so, can we tell how many papers from an individual search?

**Comment by markwilliamfirth** [comment]
@ajburls thank you for moving this one in to sprint 3, in order to time estimate this we need to clarify the requirements for this issue. Are these the updated requirements?

- [ ] Tracking which papers the user clicked through to from a search
- [ ] The total number of papers they clicked through to per individual search

**Comment by Cleop** [comment]
@markwilliamfirth I think this issue is a bit out of line. I wouldn't gather the metrics outlined here via google analytics, this is the data that we store in our database. I think this has more to do with #146 and admin functionality.

**Comment by markwilliamfirth** [comment]
@Cleop yes GA might not be the solution here - however we still need to clarify the requirements and can then change the solution accordingly

**Comment by ajburls** [comment]
@markwilliamfirth @Cleop @SimonLab 

It could well be that I am muddling things up as there definitely seem to be several different but interrelated issues. For example in Admin Functionality #20 I wrote that for us to evaluate the MVP and be able to give figures to funders, the adminstrator needs to be able to find out:

-  content of searches (linking these to individual users)
-  date of searches
-  articles clicked through to from each search
-  notes made about search
-  notes made about question

I assumed that the above would be done be analysing database and that the following could be done by routine analytics.

1. - Total number of registered users
2. -  Number of searches made in last day/week/month/year/all time in total and by user
3. -  Proportion of registered users that have used app in last day/week/month/year/all time
4. -  Average number of searches per user
5. -  Average number of papers clicked through to per search
6. -  Number of searches with notes
7. -  Number of searches with completed notes
8. -  Number of papers clicked through to with incomplete notes
9. -  Proportion of papers clicked through to with incomplete notes
10. -  Number of papers clicked through to with completed notes
11. -  Proportion of papers clicked through to with completed notes
12. -  Database search functionality (e.g. filter by different data such as date of search or single user ID) 

In the light of Marks comments it may be that some of these can come from Google analytics but some will need to come from pre-configured searches of the database that can be run easily. Dwyl would have to advise which are which.

It would be helpful to me to have a list of what Google analytics could tell me and also I would need to be taught how to run these or find these. 

Then we could work out how to address finding out the other information by SQL dashboard linked to database. Mark you might want to close this issue and separate out the component issues in a way that makes sense from the development side.

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/best-evidence/issues/194
